- name: generate random id
  ansible.builtin.shell: sleep 1 ; date | md5sum | awk '{print$1}'
  register: random

- name: create job template
  ansible.builtin.template:
    src: m-pipeline.xml
    dest: /tmp/m-pipeline.xml
  vars:
    random_id: "{random.stdout}"

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-pipeline.xml') }}"
    name: "CI-Pipelines/{{item}}"
    password: Cisco@410
    url: http://172.31.7.106:8080/
    user: admin
