- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/s-pipeline.xml') }}"
    name: test
    password: 114baa9b42ce9bcf2b03eb5b13c77e30df
    url: http://http://172.31.4.221:8080/
    user: admin