- name: create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: Cisco@410
    url: http://172.31.7.106:8080/
    user: admin
  loop:
    - CI-Pipelines

- name: Include pipeline tasks
  ansible.builtin.include_tasks: s-pipelines.yml
  vars:
    COMPONENT: "{{item}}"
  loop:
    - frontend
    - catalogue
    - user
    - cart
    - shipping
    - payment

